# TorosamyItem生成的物品禁止进入哪些容器
# 更多请见https://bukkit.windit.net/javadoc/org/bukkit/event/inventory/InventoryType.html
black-container:
  - ANVIL
  - BEACON
  - BLAST_FURNACE
  - BREWING
  - CARTOGRAPHY
  - CHISELED_BOOKSHELF
  - COMPOSTER
  - CRAFTING
  - CRAFTER
  - DISPENSER
  - DROPPER
  - ENCHANTING
  - FURNACE
  - GRINDSTONE
  - HOPPER
  - JUKEBOX
  - LECTERN
  - LOOM
  - MERCHANT
  - SMITHING
  - SMOKER
  - STONECUTTER
  - WORKBENCH
# - BARREL # 木桶，有27个集装箱类型的槽。

catalog-default-item:
  display: "&e装饰线"
  material: GRAY_STAINED_GLASS_PANE
  lore: []
  enchantment:
    - DURABILITY:1
  item-flag-list:
    - "HIDE_ATTRIBUTES"
    - "HIDE_ENCHANTS"
  slots:
    - 0
    - 9
    - 18
    - 27
    - 36
    - 45
    - 8
    - 17
    - 26
    - 35
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7