# TorosamyItem生成的物品禁止进入哪些容器
# 更多请见https://bukkit.windit.net/javadoc/org/bukkit/event/inventory/InventoryType.html
black-container:
  - ANVIL
  - BEACON
  - BLAST_FURNACE
  - BREWING
  - CARTOGRAPHY
  - CHISELED_BOOKSHELF
  - COMPOSTER
  - CRAFTING
  - CRAFTER
  - DISPENSER
  - DROPPER
  - ENCHANTING
  - FURNACE
  - GRINDSTONE
  - HOPPER
  - JUKEBOX
  - LECTERN
  - LOOM
  - MERCHANT
  - SMITHING
  - SMOKER
  - STONECUTTER
  - WORKBENCH
# - BARREL # 木桶，有27个集装箱类型的槽。

remove-unload-item: true

catalog-default-item:
  display: "&e装饰线"
  material: GRAY_STAINED_GLASS_PANE
  lore:
    - "&6&m                     "
    - "&e&l ▪ 左键查看更新日志"
    - "&e&l ▪ 右键查看活动内容"
    - "&6&m                     "
  enchantment:
    - DURABILITY:1
  item-flag-list:
    - "HIDE_ATTRIBUTES"
    - "HIDE_ENCHANTS"
  right-commands: 
    - '[player] item-catalog'
  left-commands:
    - '[player] item-catalog'